### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by kaixinol** [HaroldRoot/tumblr-to-markdown#1]
https://github.com/HaroldRoot/tumblr-to-markdown/blob/3393e4d374971b7ff06cdf95b1f0ca86fdae0c20/main.py#L9
用`concurrent.futures.ThreadPoolExecutor`并发
https://github.com/HaroldRoot/tumblr-to-markdown/blob/3393e4d374971b7ff06cdf95b1f0ca86fdae0c20/main.py#L155-L156
用`\t`或者`'-'*10`
https://github.com/HaroldRoot/tumblr-to-markdown/blob/3393e4d374971b7ff06cdf95b1f0ca86fdae0c20/main.py#L166-L173
用`match-case`结构
**def函数**
没有用self的用`@staticmethod`装饰器
https://github.com/HaroldRoot/tumblr-to-markdown/blob/3393e4d374971b7ff06cdf95b1f0ca86fdae0c20/main.py#L293-L297
用`'''多行文本'''`
https://github.com/HaroldRoot/tumblr-to-markdown/blob/3393e4d374971b7ff06cdf95b1f0ca86fdae0c20/main.py#L287-L339
`-> None`多余，这些函数也多余，需要重写。 `names[0] == ""`改成` not len(names[0])`

用`tomllib`做配置文件

**Comment by HaroldRoot** [comment]
Done.
